// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsCOIpHzNx6JL7GLlqVXNBRTOH6p4bTG4',
    appId: '1:892999471150:web:2c13b4fe1e5d07df768fbf',
    messagingSenderId: '892999471150',
    projectId: 'ku-kesk-vaela-8',
    authDomain: 'ku-kesk-vaela-8.firebaseapp.com',
    storageBucket: 'ku-kesk-vaela-8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSqsgcu6mykpAYXcpt0cpi1bux0ddKby4',
    appId: '1:892999471150:android:35258015c3934e31768fbf',
    messagingSenderId: '892999471150',
    projectId: 'ku-kesk-vaela-8',
    storageBucket: 'ku-kesk-vaela-8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO8urkGMInfWAIiVFuUQx1m6B7UPNXgbY',
    appId: '1:892999471150:ios:5c162b57fa96471c768fbf',
    messagingSenderId: '892999471150',
    projectId: 'ku-kesk-vaela-8',
    storageBucket: 'ku-kesk-vaela-8.firebasestorage.app',
    iosClientId: '892999471150-mke33fopt8o79psd0cs2us02h635pahd.apps.googleusercontent.com',
    iosBundleId: 'ee.masoov.apartment',
  );
}
